// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CookingFit.Web.Models;

public partial class Cardapio
{
    public int IdCardapio { get; set; }

    public string Descriçao { get; set; }

    public int IdUsuario { get; set; }

    public int IdReceita { get; set; }

    public int IdIngrediente { get; set; }

    public int? Quantidade { get; set; }

    public int? CaloriasCardapio { get; set; }

    public virtual Ingrediente IdIngredienteNavigation { get; set; }

    public virtual Receita IdReceitaNavigation { get; set; }

    public virtual ICollection<Usuário> Usuários { get; set; } = new List<Usuário>();
}