// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CookingFit.Web.Models;

public partial class Funcionario
{
    public int IdDepartamento { get; set; }

    public string Departamento { get; set; }
}