// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CookingFit.Web.Models;

public partial class Ingredientesreceita
{
    public int IdReceita { get; set; }

    public int IdIngrediente { get; set; }

    public DateTime DataCriação { get; set; }

    public int Quantidade { get; set; }

    public virtual Ingrediente IdIngredienteNavigation { get; set; }

    public virtual Receita IdReceitaNavigation { get; set; }
}