// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CookingFit.Web.Models;

public partial class Ingrediente
{
    public string Nome { get; set; }

    public int IdIngrediente { get; set; }

    public int Calorias { get; set; }

    public string Unidade { get; set; }

    public string Peso { get; set; }

    public virtual ICollection<Cardapio> Cardapios { get; set; } = new List<Cardapio>();
}