// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CookingFit.Web.Models;

public partial class Usuário
{
    public string Nome { get; set; }

    public string EMail { get; set; }

    public string Cpf { get; set; }

    public DateTime DtNasc { get; set; }

    public int IdUsuario { get; set; }

    public string Genero { get; set; }

    public int? Telefone { get; set; }

    public string FormAcademica { get; set; }

    public int Peso { get; set; }

    public decimal Altura { get; set; }

    public int Idade { get; set; }

    public int? IdCardapio { get; set; }

    public virtual Cardapio IdCardapioNavigation { get; set; }
}