// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CookingFitDATA.Models;

[Table("Cardapio")]
public partial class Cardapio
{
    [Key]
    [Column("id_cardapio")]
    public int IdCardapio { get; set; }

    [Column("descriçao")]
    [StringLength(255)]
    [Unicode(false)]
    public string Descriçao { get; set; }

    [Column("id_usuario")]
    public int IdUsuario { get; set; }

    [Column("id_receita")]
    public int IdReceita { get; set; }

    [Column("id_ingrediente")]
    public int IdIngrediente { get; set; }

    [Column("quantidade")]
    public int? Quantidade { get; set; }

    [Column("calorias_cardapio")]
    public int? CaloriasCardapio { get; set; }

    [ForeignKey("IdIngrediente")]
    [InverseProperty("Cardapios")]
    public virtual Ingrediente IdIngredienteNavigation { get; set; }

    [ForeignKey("IdReceita")]
    [InverseProperty("Cardapios")]
    public virtual Receita IdReceitaNavigation { get; set; }

    [InverseProperty("IdCardapioNavigation")]
    public virtual ICollection<Usuário> Usuários { get; set; } = new List<Usuário>();
}