// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CookingFitDATA.Models;

[Table("funcionario")]
public partial class Funcionario
{
    [Key]
    [Column("id_departamento")]
    public int IdDepartamento { get; set; }

    [Required]
    [Column("departamento")]
    [StringLength(255)]
    [Unicode(false)]
    public string Departamento { get; set; }
}