// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CookingFitDATA.Models;

public partial class Ingrediente
{
    [Required]
    [Column("nome")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Key]
    [Column("id_ingrediente")]
    public int IdIngrediente { get; set; }

    [Column("calorias")]
    public int Calorias { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Unidade { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Peso { get; set; }

    [InverseProperty("IdIngredienteNavigation")]
    public virtual ICollection<Cardapio> Cardapios { get; set; } = new List<Cardapio>();
}