// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CookingFitDATA.Models;

public partial class Receita
{
    [Required]
    [Column("nome")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Key]
    [Column("ID_receita")]
    public int IdReceita { get; set; }

    [Required]
    [Column("descriçao")]
    [StringLength(255)]
    [Unicode(false)]
    public string Descriçao { get; set; }

    [Column("ativo")]
    public bool Ativo { get; set; }

    [InverseProperty("IdReceitaNavigation")]
    public virtual ICollection<Cardapio> Cardapios { get; set; } = new List<Cardapio>();
}