// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CookingFitDATA.Models;

[Table("Usuário")]
public partial class Usuário
{
    [Required]
    [Column("nome")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("e-mail")]
    [StringLength(255)]
    [Unicode(false)]
    public string EMail { get; set; }

    [Required]
    [Column("CPF")]
    [StringLength(255)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Column("dt_nasc", TypeName = "date")]
    public DateTime DtNasc { get; set; }

    [Key]
    [Column("id_usuario")]
    public int IdUsuario { get; set; }

    [Required]
    [Column("genero")]
    [StringLength(10)]
    [Unicode(false)]
    public string Genero { get; set; }

    [Column("telefone")]
    public int? Telefone { get; set; }

    [Column("form_academica")]
    [StringLength(255)]
    [Unicode(false)]
    public string FormAcademica { get; set; }

    [Column("peso")]
    public int Peso { get; set; }

    [Column("altura", TypeName = "decimal(18, 0)")]
    public decimal Altura { get; set; }

    [Column("idade")]
    public int Idade { get; set; }

    [Column("id_cardapio")]
    public int? IdCardapio { get; set; }

    [ForeignKey("IdCardapio")]
    [InverseProperty("Usuários")]
    public virtual Cardapio IdCardapioNavigation { get; set; }
}